# SearXJP settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXJP"

server:
  # Change it
  secret_key: "ultrasecretkey"
  limiter: true
  public_instance: false

valkey:
  url: valkey://localhost:6379/0
